### ISSUE TITLE
transparency color changed

### ISSUE THREAD

**Issue by EssenRoc** [Suprcode/mir2#260]
I upgraded to the latest version, but why does the color of transparency change?

Original：
![00](https://user-images.githubusercontent.com/12685126/32319060-28848cf6-bff4-11e7-8db2-1e7bb661b1d3.jpg)

Before upgrade：
![11](https://user-images.githubusercontent.com/12685126/32319044-1daef56e-bff4-11e7-9c62-8fe9e8e2f5df.jpg)

After upgrade：
![22](https://user-images.githubusercontent.com/12685126/32319047-1f1d419e-bff4-11e7-8fd5-61e175b3214b.jpg)

Thank you!

**Comment by lodos3** [comment]
Because you're login scene BackColour has no set colour and automatically assumes it's white.
To fix this, set the LoginScene Back Colour to Color.Fromargb(1,1,1,1)


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Roc <notifications@github.com> Date: 02/11/2017  09:35  (GMT+00:00) To: Suprcode/mir2 <mir2@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [Suprcode/mir2] transparency color changed (#260) 
I upgraded to the latest version, but why does the color of transparency change?
Original：


Before upgrade：


After upgrade：


Thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Suprcode/mir2","title":"Suprcode/mir2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Suprcode/mir2"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"transparency color changed (#260)"}],"action":{"name":"View Issue","url":"https://github.com/Suprcode/mir2/issues/260"}}}

**Comment by EssenRoc** [comment]
@lodos3 Background color default is transparent(ARGB=(0, 0, 0, 0))

**Comment by lodos3** [comment]
Yeah I know, which returns WHITE IF you overlay it with opaque images.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Roc <notifications@github.com> Date: 02/11/2017  23:21  (GMT+00:00) To: Suprcode/mir2 <mir2@noreply.github.com> Cc: lodos3 <djgozzett@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Suprcode/mir2] transparency color changed (#260) 
@lodos3 Background color default is transparent(ARGB=(0, 0, 0, 0))

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Suprcode/mir2","title":"Suprcode/mir2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Suprcode/mir2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@EssenRoc in #260: @lodos3 Background color default is transparent(ARGB=(0, 0, 0, 0))"}],"action":{"name":"View Issue","url":"https://github.com/Suprcode/mir2/issues/260#issuecomment-341586770"}}}

**Comment by EssenRoc** [comment]
@lodos3 DXManager.Device.Clear(ClearFlags.Target, Color.CornflowerBlue, 0, 0); Changed to Color.Black ...
