### ISSUE TITLE
Why not draw the same?

### ISSUE THREAD

**Issue by EssenRoc** [Suprcode/mir2#263]
![1](https://user-images.githubusercontent.com/12685126/33950669-f43fc8ae-e067-11e7-9f16-8a1b6c7f60c8.png)

image 1:
`Libraries.???.Draw(1, 20, 20)`

image 2:
`MirImageControl`

image 2 no border shadows

**Comment by EssenRoc** [comment]
What settings do I need to make? Thanks!

**Comment by EssenRoc** [comment]
GameScene.BackColour = Color.Transparent;

**Comment by EssenRoc** [comment]
@Suprcode what should I do?

**Comment by EssenRoc** [comment]
try:
`
GameScene.BackColour = Color.White;
`
![2](https://user-images.githubusercontent.com/12685126/33982109-456c7fd8-e0ea-11e7-9c5e-a002341e7835.png)

but no map!!! help me!

**Comment by daneo1989** [comment]
Why not post on LOMCN you will get faster responses, And this is not a source issue.

**Comment by EssenRoc** [comment]
@daneo1989  look this: http://www.lomcn.org/forum/showthread.php?98279-Why-not-draw-the-same

**Comment by lodos3** [comment]
GameScene.BackColour = Color.FromArgb(1,1,1,1)

Although "Transparent" appears transparent, anything overlaying it with a
slight fade, will either be removed or appear greyish (basically because it
simulates Opaque pixels over white, and not black ...which is generally
preferred). Using the above setting simulates Black for opaque pixels, this
makes any opaque overlays over the back scene appear less grey and could
possibly fix your problem. That being said, Shanda uses a shadow around
their Images (rather than via code) and they use two methods of clearing.
One method to make anything that's 080808 opaque and anything 000000
(black) clear/transparent.

**Comment by EssenRoc** [comment]
fix this.
