### ISSUE TITLE
Can not edit form

### ISSUE THREAD

**Issue by w43869121** [Suprcode/mir2#272]
Can not edit form
I am an amateur, or I build the environment is not right ah?
Please report the screenshot 。

![qq 20180225105332](https://user-images.githubusercontent.com/36805284/36637663-e40da972-1a1b-11e8-9a6e-9f6a799af2ee.png)
![qq 20180225105259](https://user-images.githubusercontent.com/36805284/36637664-e4778cca-1a1b-11e8-9ea3-d5265da3a818.png)

**Comment by RyanTaplin1705** [comment]
Either the implementation of PlayersOnlineListView is not recognised by VisualStudio or some code has been removed/ edited so that visual studio can't compile/ render it. 

Is this currently happening in main source? Don't think I have seen this issue (unless I have been editing forms myself and added/removed something poorly).

I think this can be closed tbh @Suprcode
