### ISSUE TITLE
About adding necessary detection commands

### ISSUE THREAD

**Issue by angelk727** [Suprcode/mir2#535]
It is suggested to add death detection. The biggest and most difficult bug in the current version is that people can never exit after death, or even have to call the system's resource manager to cut off the program. (IOS not tested) the simplest test method: enter the "die" command after the character logs in, and click "no" after the dialog box appears. Then press any skill key (there must be a skill). Then click a small or large retreat. You will usher in a never-ending Task.

**Comment by Suprcode** [comment]
It's not just about saving space, which as you say is not much.

There is no need to fake blank frames for any monster. Just because it's the easier approach, it doesn't mean that's how you should do it.

No previous monster has had to add fake frames, so i expect it is not needed here.

Please spend time to write the AI in the best way.
