### ISSUE TITLE
Attack Ranges of bosses should match their database info

### ISSUE THREAD

**Issue by EliteMir** [Suprcode/mir2#689]
You have bosses with view ranges of 14 but their AI has attack ranges of 6, which causes them to get stuck usually and just stand around not casting their ranged abilities.

Both should match to prevent constant recoding of boss AIs

**Comment by Suprcode** [comment]
They shouldn't match. The point of view range is to assert when a monster can see you, and potentially start walking towards you for a "target"

It might still only have an attack range of 2 if its a close up attack.

**Comment by EliteMir** [comment]
Then it likely needs to be increased to the same as the attack range.

Bosses can be trapped and don't attack because the ranged attacks are set to 6 but the players can attack from 9.

Trap and just stay at max range and the bosses spaz out.

**Comment by Suprcode** [comment]
All AI's have an "InAttackRange" function that checks if their range attack can be used - if not, the AI code will usually default to the monster walking towards the target until they are within range.

If the monster does not walk towards the target and just stands still even though they're in view range then the issue is down to that individual AI - not a generic issue that happens on every monster.

Also if a monster is not in view range (because its set to 6) and the monster is attacked from 9 coords away - the AI will be given a target and will start to walk towards it.

Maybe give an example of a monster AI which isn't working as you expect.
