### ISSUE TITLE
Mass adding Safezones

### ISSUE THREAD

**Issue by JevLOMCN** [Suprcode/mir2#796]
You can't select more the one map and add Safezones.

![image](https://user-images.githubusercontent.com/68875342/233842952-765eeb8d-1cb0-4b49-94fa-a98f948d7982.png)

**Comment by Suprcode** [comment]
not really a bug, just a limitation of what can be updated on mass.

You'll have the exact same result with any button (remove safezone, add respawn, add movement, add minezone etc) i suspect.

To me its a pretty useless thing to need for maps, since the only time you'll need to add it in bulk are for instance maps.

Maybe instead of adding the "bulk update" functionality to everything, just have a "clone map" button and remove mult select altogether.

**Comment by grimchamp** [comment]
Agreed - not an issue.
