### ISSUE TITLE
%InputStr bug

### ISSUE THREAD

**Issue by damianday** [Suprcode/mir2#910]
Cannot be used with the default NPC

**Comment by Suprcode** [comment]
Not a bug as such. It's a security limitation that external windows like goods or input system must be rooted to a physical NPC that a player is stood near - so that hacked clients can't access them from an area they shouldn't.

You could probably adjust the security check to ignore it for 00default calls though

**Comment by damianday** [comment]
NPCConfirmInput in MirConnection.cs could just have something similar to CallNPC where it checks if the current NPC is your default NPC and call the correct script. I can't see an exploit, but I didn't really look, just came as a surprise when my script half worked, it pops up the input dialogue but can't complete the response.
